#!/bin/bash
#PBS -l nodes=1:ppn=4,vmem=64gb,walltime=02:00:00
#PBS -N bl.set-bad-channels

#SBATCH --ntasks-per-node=4
#SBATCH --mem=64G
#SBATCH --time=02:00:00

set -e
set -x

singularity exec docker://brainlife/mne:1.2.1 python3 main.py
