#!/bin/bash
#PBS -l nodes=1:ppn=1,vmem=8gb,walltime=00:30:00
#PBS -N bl.set-bad-channels

#SBATCH --ntasks-per-node=1
#SBATCH --mem=8G
#SBATCH --time=00:30:00

set -e
set -x

singularity exec docker://brainlife/mne:1.2.1 python3 main.py
